exclude: |
  (?x)^(
      .*assets/.*|
      .*coverage/.*
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              .*\.sql
          )$
      - id: detect-private-key
      - id: debug-statements
      - id: pretty-format-json
        exclude: |
          (?x)^(
              .*json_schema.*
          )$
        args: ["--autofix"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-added-large-files
        args: ["--maxkb=5000"]
